### ISSUE TITLE
Custom ops are incompatible with Tensorflow Java SDK

### ISSUE THREAD

**Issue by mattdornfeld** [tensorflow/decision-forests#101]
Hello! I'm working on serving a tfdf model with the Java SDK. I tried the solution describe [here](https://github.com/tensorflow/decision-forests/issues/81), where you pass the compiled .so file for the tf-df library to `TensorFlow.loadLibrary` before calling `SavedModelBundle.load`. I ran into this exception 

```
        Caused by:
        org.tensorflow.exceptions.TFInvalidArgumentException: No shape inference function exists for op 'SimpleMLLoadModelFromPathWithHandle', did you forget to define it?
            at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:87)
            at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:623)
            at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:67)
            at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:97)
            at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:357)
```

It seems like there's an issue with the custom ops defined as part of this library in that they don't implement the `SetShapeFn`. Any idea on how much work it would be to fix this compatibility issue?

**Comment by achoum** [comment]
TF-DF ops are now compatible with TF Java. See [this issue](https://github.com/tensorflow/decision-forests/issues/81) for more details.
