### ISSUE TITLE
tensorflow_decision_forests save_model error

### ISSUE THREAD

**Issue by Zjq9409** [tensorflow/decision-forests#142]
if I use model.prefict() directly after model.fit(), there is no error. While I save model, then use model.predict() function in other function, I will got follow erros.
```
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_decision_forests as tfdf
import time

class MLforKidsNumberProject(object):
    def __init__(self, *args, **kwargs):
        super()
    
    def get_datasets(self, PATH: str):
        train = pd.read_csv(PATH)
        label = "label"
        train_ds = tfdf.keras.pd_dataframe_to_tf_dataset(train, label=label)
        classes = train[label].unique().tolist()
        print (f"Label classes are hiven as>>>>>>>>>>>>>: {classes}")
        return train_ds

    def define_model(self):   
        METRICS=["accuracy"]
        MODEL_CATEGORICAL_ALGORITHM = "RANDOM"
        model = tfdf.keras.RandomForestModel(
            min_examples = 1,
            num_trees = 100,
            verbose=1,
            random_seed = 42,
            categorical_algorithm=MODEL_CATEGORICAL_ALGORITHM
        )
        model.compile(metrics=METRICS)
        return model
    
    def train_model(self, PATH:str):
        train_ds = self.get_datasets(PATH)
        model = self.define_model()
        model.fit(train_ds)
        test = pd.read_csv(TEST_PATH)
        model_path = "/tmp/number_model/" + str(int(time.time()))
        model.save(model_path, overwrite=True)
        return model_path, None

    def prediction(self, PATH:str, model_path, label_dict):
        model = tf.keras.models.load_model(model_path)
        test = pd.read_csv(PATH)
        test_ds = tfdf.keras.pd_dataframe_to_tf_dataset(test)
        output = model.predict(test_ds)
        print(output)
        print((output > 0.5).astype(int))

if __name__ == "__main__":
    TRAIN_PATH = "./data/train.csv"
    TEST_PATH = "./data/test.csv"
    trainer = MLforKidsNumberProject()
    model_path, label_dict = trainer.train_model(TRAIN_PATH)
    trainer.prediction(TEST_PATH, model_path, label_dict)
```

```

[INFO kernel.cc:1176] Loading model from path /tmp/number_model/1667983650/assets/ with prefix 709ac031679e4301
[INFO decision_forest.cc:639] Model loaded with 100 root(s), 20842 node(s), and 4 input feature(s).
[INFO kernel.cc:1022] Use fast generic engine
Traceback (most recent call last):
  File "train_number.py", line 64, in <module>
    trainer.prediction(TEST_PATH, model_path, label_dict)
  File "train_number.py", line 54, in prediction
    output = model.predict(test_ds)
  File "/home/jane/anaconda3/envs/bigdl/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_file2k6hu6zu.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "/home/jane/anaconda3/envs/bigdl/lib/python3.7/site-packages/keras/engine/training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "/home/jane/anaconda3/envs/bigdl/lib/python3.7/site-packages/keras/engine/training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/jane/anaconda3/envs/bigdl/lib/python3.7/site-packages/keras/engine/training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "/home/jane/anaconda3/envs/bigdl/lib/python3.7/site-packages/keras/engine/training.py", line 1983, in predict_step
        return self(x, training=False)
    File "/home/jane/anaconda3/envs/bigdl/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "random_forest_model" "                 f"(type RandomForestModel).
    
    Could not find matching concrete function to call loaded from the SavedModel. Got:
      Positional arguments (2 total):
        * {'age': <tf.Tensor 'inputs:0' shape=(None,) dtype=int64>,
     'class': <tf.Tensor 'inputs_1:0' shape=(None,) dtype=int64>,
     'fare': <tf.Tensor 'inputs_2:0' shape=(None,) dtype=float32>,
     'gender': <tf.Tensor 'inputs_3:0' shape=(None,) dtype=string>}
        * False
      Keyword arguments: {}
    
     Expected these arguments to match one of the following 4 option(s):
    
    Option 1:
      Positional arguments (2 total):
        * {'age': TensorSpec(shape=(None,), dtype=tf.float32, name='inputs/age'),
     'class': TensorSpec(shape=(None,), dtype=tf.int64, name='inputs/class'),
     'fare': TensorSpec(shape=(None,), dtype=tf.float32, name='inputs/fare'),
     'gender': TensorSpec(shape=(None,), dtype=tf.string, name='inputs/gender')}
        * False
      Keyword arguments: {}
    
    Option 2:
      Positional arguments (2 total):
        * {'age': TensorSpec(shape=(None,), dtype=tf.float32, name='inputs/age'),
     'class': TensorSpec(shape=(None,), dtype=tf.int64, name='inputs/class'),
     'fare': TensorSpec(shape=(None,), dtype=tf.float32, name='inputs/fare'),
     'gender': TensorSpec(shape=(None,), dtype=tf.string, name='inputs/gender')}
        * True
      Keyword arguments: {}
    
    Option 3:
      Positional arguments (2 total):
        * {'age': TensorSpec(shape=(None,), dtype=tf.float32, name='age'),
     'class': TensorSpec(shape=(None,), dtype=tf.int64, name='class'),
     'fare': TensorSpec(shape=(None,), dtype=tf.float32, name='fare'),
     'gender': TensorSpec(shape=(None,), dtype=tf.string, name='gender')}
        * False
      Keyword arguments: {}
    
    Option 4:
      Positional arguments (2 total):
        * {'age': TensorSpec(shape=(None,), dtype=tf.float32, name='age'),
     'class': TensorSpec(shape=(None,), dtype=tf.int64, name='class'),
     'fare': TensorSpec(shape=(None,), dtype=tf.float32, name='fare'),
     'gender': TensorSpec(shape=(None,), dtype=tf.string, name='gender')}
        * True
      Keyword arguments: {}
    
    Call arguments received by layer "random_forest_model" "                 f"(type RandomForestModel):
      • args=({'class': 'tf.Tensor(shape=(None,), dtype=int64)', 'gender': 'tf.Tensor(shape=(None,), dtype=string)', 'age': 'tf.Tensor(shape=(None,), dtype=int64)', 'fare': 'tf.Tensor(shape=(None,), dtype=float32)'},)
      • kwargs={'training': 'False'}
```
train_data.csv as follows:
class	gender	age	fare	label
1	female	50.0	28.7125	died
1	female	2.0	151.55	died
1	female	25.0	151.55	died
1	male	38.0	0.0	died
1	male	39.0	0.0	died
1	male	40.0	0.0	died
1	male	33.0	5.0	died
2	female	24.0	13.0	survived

test_data.csv as follows
class	gender	age	fare
3	male	24	7.1417
1	male	47	227

**Comment by rstz** [comment]
Hi,

thank you for the detailed report. Your test dataset has "age" stored as integer, while your training dataset has "age" stored as float64. Hence there is a mismatch between data types between training and test data, which raises the error. 
The simplest fix would be to either modify the test data or set the correct type manually with `test = test.astype({"age": np.float64})` after reading the dataset with pandas.

The issue indeed only occurs when with a loaded model. This is, unfortunately, a known quirk of TF-DF / Keras. 
You can find [more details here](https://www.tensorflow.org/decision_forests/tutorials/predict_colab#important_remark).

**Comment by rstz** [comment]
I added a warning about this to the known issues.
