### ISSUE TITLE
WARNING:root:Failure to load the inference.so custom c++ tensorflow ops

### ISSUE THREAD

**Issue by Matsika** [tensorflow/decision-forests#217]
Hi,

I have tensorflow 2.15.0 and tensorflow_decision_forests  1.8.1 and according to the website, I know that these are compatible, but for some reason when I try import tensorflow_decision_forests as tfdf I keep getting the following error:
 import tensorflow_decision_forests as tfdf
WARNING:root:Failure to load the inference.so custom c++ tensorflow ops. This error is likely caused the version of TensorFlow and TensorFlow Decision Forests are not compatible. Full error:/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/__init__.py", line 64, in <module>
    from tensorflow_decision_forests import keras
  File "/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/keras/__init__.py", line 53, in <module>
    from tensorflow_decision_forests.keras import core
  File "/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/keras/core.py", line 62, in <module>
    from tensorflow_decision_forests.keras import core_inference
  File "/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/keras/core_inference.py", line 36, in <module>
    from tensorflow_decision_forests.tensorflow.ops.inference import api as tf_op
  File "/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/tensorflow/ops/inference/api.py", line 179, in <module>
    from tensorflow_decision_forests.tensorflow.ops.inference import op
  File "/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/tensorflow/ops/inference/op.py", line 15, in <module>
    from tensorflow_decision_forests.tensorflow.ops.inference.op_dynamic import *
  File "/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/tensorflow/ops/inference/op_dynamic.py", line 24, in <module>
    raise e
  File "/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/tensorflow/ops/inference/op_dynamic.py", line 21, in <module>
    ops = tf.load_op_library(resource_loader.get_path_to_datafile("inference.so"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow/python/framework/load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.NotFoundError: /global/scratch/users/tmatsika/bf_python/lib/python3.11/site-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: cannot open shared object file: No such file or directory

I have looked at the other issues and I didn't find a solution that worked for me. I'm using a system with arm64 architecture.

**Comment by Matsika** [comment]
Hello,

Could I please get some help with this issue please. I have a very big deadline to meet.

**Comment by Elainelovewatermelon** [comment]
I also have the same problem, did you figure it out?

**Comment by Matsika** [comment]
No, I'm hoping that the developers will know how to fix the issue. I think the issue is that TensorFlow Decision Forests doesn't work on linux arm64 architecture, but it does work on Mac arm so I think it's something the developers may need to update so that it works on linux arm64.

**Comment by Elainelovewatermelon** [comment]
I find out that there is an extension called tensorflow in vscode, do you know if it also contains tensorflow decision forest?

**Comment by rstz** [comment]
Hi, while I believe that it is possible to compile TF-DF on ARM64 Linux, it's not something we've looked into in more detail. I might have a closer look, but absolutely no promises, and I don't think we have the bandwidth to officially support another architecture at this time for TF-DF. 

> 
I find out that there is an extension called tensorflow in vscode, do you know if it also contains tensorflow decision forest?

Very likely not.

**Comment by ekworp** [comment]
I still have this problem on 1.9

**Comment by HashemZn-04** [comment]
I have this exact problem but on Windows, have you found a solution to this yet?

**Comment by fahminlb33** [comment]
I also encountered the same problem, it turns out to be a [compatibility issue](https://www.tensorflow.org/decision_forests/known_issues). If you install `tensorflow` using `conda` and `tensorflowjs` using `pip`, this issue still happens even when you have a compatible version.

My workaround is uninstall tensorflow using `conda remove tensorflow` and reinstalling it using `pip install tensorflow==2.15.0 tensorflowjs`

**Comment by TheRealCasmat** [comment]
I'm starting to face this issue using tfjs on arm64 ubuntu. inference.so couldn't be found. This should be looked into further

**Comment by nicklasb** [comment]
@TheRealCasmat, @rstz 
Same issue here on Windows 11.

**Comment by Gpaio574** [comment]
Same issue on Windows 11.

**Comment by AlperenOvak** [comment]
Same problem on Windows 11

**Comment by CisseBenn** [comment]
Did anyone find the solution? I've been stuck for 2 days

**Comment by ekworp** [comment]
because it only supports linux x86 or macosx arm64, reference: https://pypi.org/project/tensorflow-decision-forests/#files

**Comment by CisseBenn** [comment]
Windows is slowly loosing me😅
